[package]
name = "aseprite-packer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asefile = "0.2.0"
image = "0.23.14"
texture_packer = "0.23.0"